--GRANTS
-- Acesso total em DEV
GRANT ALL PRIVILEGES ON DATABASE DEV_RAW TO ROLE ENGENHEIRO_DADOS;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE DEV_RAW TO ROLE ENGENHEIRO_DADOS;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA DEV_RAW.OPENMETEO TO ROLE ENGENHEIRO_DADOS;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA DEV_RAW.CAGED TO ROLE ENGENHEIRO_DADOS;

GRANT ALL PRIVILEGES ON DATABASE DEV_STG TO ROLE ENGENHEIRO_DADOS;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE DEV_STG TO ROLE ENGENHEIRO_DADOS;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA DEV_STG.OPENMETEO TO ROLE ENGENHEIRO_DADOS;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA DEV_STG.CAGED TO ROLE ENGENHEIRO_DADOS;

--Grants automaticos para os proximos schemas e tabelas 
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE DEV_RAW TO ROLE ENGENHEIRO_DADOS;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE DEV_STG TO ROLE ENGENHEIRO_DADOS;

GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEV_RAW.OPENMETEO TO ROLE ENGENHEIRO_DADOS;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEV_RAW.CAGED TO ROLE ENGENHEIRO_DADOS;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEV_STG.OPENMETEO TO ROLE ENGENHEIRO_DADOS;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEV_STG.CAGED TO ROLE ENGENHEIRO_DADOS;

-- Leitura em HML e PRD
GRANT USAGE ON DATABASE HML_RAW TO ROLE ENGENHEIRO_DADOS;
GRANT USAGE ON DATABASE PRD_RAW TO ROLE ENGENHEIRO_DADOS;
GRANT USAGE ON DATABASE HML_STG TO ROLE ENGENHEIRO_DADOS;
GRANT USAGE ON DATABASE PRD_STG TO ROLE ENGENHEIRO_DADOS;

GRANT USAGE ON SCHEMA HML_RAW.OPENMETEO TO ROLE ENGENHEIRO_DADOS;
GRANT USAGE ON SCHEMA HML_RAW.CAGED TO ROLE ENGENHEIRO_DADOS;
GRANT USAGE ON SCHEMA PRD_RAW.OPENMETEO TO ROLE ENGENHEIRO_DADOS;
GRANT USAGE ON SCHEMA PRD_RAW.CAGED TO ROLE ENGENHEIRO_DADOS;

GRANT SELECT ON ALL TABLES IN SCHEMA HML_RAW.OPENMETEO TO ROLE ENGENHEIRO_DADOS;
GRANT SELECT ON ALL TABLES IN SCHEMA HML_RAW.CAGED TO ROLE ENGENHEIRO_DADOS;
GRANT SELECT ON ALL TABLES IN SCHEMA PRD_RAW.OPENMETEO TO ROLE ENGENHEIRO_DADOS;
GRANT SELECT ON ALL TABLES IN SCHEMA PRD_RAW.CAGED TO ROLE ENGENHEIRO_DADOS;

