--Grant on databases HML
GRANT USAGE ON DATABASE HML_RAW TO ROLE QA_DADOS;
GRANT USAGE ON DATABASE HML_STG TO ROLE QA_DADOS;

---schemas
GRANT USAGE ON SCHEMA HML_RAW.OPENMETEO TO ROLE QA_DADOS;
GRANT USAGE ON SCHEMA HML_RAW.CAGED TO ROLE QA_DADOS;

GRANT USAGE ON SCHEMA HML_STG.OPENMETEO TO ROLE QA_DADOS;
GRANT USAGE ON SCHEMA HML_STG.CAGED TO ROLE QA_DADOS;

--Grants automaticos para os proximos schemas
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE HML_RAW TO ROLE QA_DADOS;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE HML_STG TO ROLE QA_DADOS;

GRANT SELECT ON FUTURE TABLES IN SCHEMA HML_RAW.OPENMETEO TO ROLE QA_DADOS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HML_STG.OPENMETEO TO ROLE QA_DADOS;

GRANT SELECT ON FUTURE TABLES IN SCHEMA HML_RAW.CAGED TO ROLE QA_DADOS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HML_STG.CAGED TO ROLE QA_DADOS;


-- Apenas hml
GRANT SELECT ON ALL TABLES IN SCHEMA HML_RAW.OPENMETEO TO ROLE QA_DADOS;
GRANT SELECT ON ALL TABLES IN SCHEMA HML_STG.OPENMETEO TO ROLE QA_DADOS;
GRANT SELECT ON ALL TABLES IN SCHEMA HML_RAW.CAGED TO ROLE QA_DADOS;
GRANT SELECT ON ALL TABLES IN SCHEMA HML_STG.CAGED TO ROLE QA_DADOS;



