
--Crear a Storage Integration
CREATE OR REPLACE STORAGE INTEGRATION s3_integration
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::995805900627:role/TesteExternalStageRole' -- role criada para o snowflake
STORAGE_ALLOWED_LOCATIONS = ('s3://bkt-data-openmeteo/raw/');

--Obter informações
DESC INTEGRATION s3_integration;

--criar uma database propia
CREATE OR REPLACE DATABASE METADATA_DB;

CREATE OR REPLACE SCHEMA METADATA_DB.FILE_FORMATS;

CREATE OR REPLACE SCHEMA METADATA_DB.STAGES;

--criar um objeto do tipo file format para reuso:
CREATE OR REPLACE FILE FORMAT METADATA_DB.FILE_FORMATS.PARQUET_FORMAT
  TYPE = 'PARQUET'
  COMPRESSION = 'SNAPPY'
  BINARY_AS_TEXT = TRUE;
;

CREATE OR REPLACE STAGE meu_stage_s3
URL = 's3://bkt-data-openmeteo/raw/' --nome do bucket + (path se aplicável)
STORAGE_INTEGRATION = s3_integration
FILE_FORMAT = METADATA_DB.FILE_FORMATS.PARQUET_FORMAT;


--grants:
GRANT USAGE ON DATABASE METADATA_DB TO ROLE ENGENHEIRO_DADOS;
GRANT USAGE ON SCHEMA METADATA_DB.FILE_FORMATS TO ROLE ENGENHEIRO_DADOS;
GRANT USAGE ON SCHEMA METADATA_DB.STAGES TO ROLE ENGENHEIRO_DADOS;

-- Permissão para usar o file format e stage
GRANT USAGE ON FILE FORMAT METADATA_DB.FILE_FORMATS.PARQUET_FORMAT TO ROLE ENGENHEIRO_DADOS;
GRANT USAGE ON STAGE METADATA_DB.STAGES.meu_stage_s3 TO ROLE ENGENHEIRO_DADOS;

-- Para admins (controle total)
GRANT USAGE ON DATABASE METADATA_DB TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA METADATA_DB.STAGES TO ROLE ACCOUNTADMIN;
GRANT READ ON STAGE METADATA_DB.STAGES.meu_stage_s3 TO ROLE ACCOUNTADMIN;
GRANT USAGE ON FILE FORMAT METADATA_DB.FILE_FORMATS.PARQUET_FORMAT TO ROLE ACCOUNTADMIN;